### ISSUE TITLE
Переделать страницу с логином под модал

### ISSUE THREAD

**Issue by luckykeks** [dressyourkid/kid-shop-ui#2]
Должна иметь в себе все  тоже самое что и на данный момент страница с логином 
филд логин, филд пароль, кнопки авторизации
сделать надо через v-dialog
https://vuetifyjs.com/en/components/dialogs#modal
разместить в components/modals/
назвать login-modal
и подключить на все страницы

**Comment by lconnected** [comment]
Сразу скажу, что нужна кнопка "Войти через ВК", без стиля, без дизайна, но нужна.
